name: Build Kernel

on:
  workflow_dispatch:   # manual trigger
  push:                # auto trigger on push
    branches:
      - "14-DSPocd"    # change if you want another branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4

      - name: Setup Build Environment
        run: |
          sudo apt-get update
          sudo apt-get inst
